### ISSUE TITLE
Selected Item Crashes Bindings In DataGrid

### ISSUE THREAD

**Issue by ChernayaKoshka** [cmeeren/Elmish.WPF.Recursive#1]
Hello,

I am currently using your library to develop a GUI application that has a data grid and a text box. The data grid's contents are supposed to be filtered out based on the contents of the text box. I also need to bind the currently selected item in the data grid so I can display internal data in it. However, when an item that is selected gets filtered out, it causes the program to crash with the following exception:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=FSharp.Core
  StackTrace:
   at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
   at Elmish.WPF.Recursive.Binding.twoWay@57-2.Invoke(Object x) in [path to lib]\Elmish.WPF.Recursive-master\src\Elmish.WPF.Recursive\Binding.fs:line 57
   at Elmish.WPF.Recursive.Binding.twoWay@57-3.Invoke(Object x) in [path to lib]\Elmish.WPF.Recursive-master\src\Elmish.WPF.Recursive\Binding.fs:line 57
   at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2)
   at Elmish.WPF.Recursive.Internal.ViewModel`2.TrySetMember(SetMemberBinder binder, Object value) in [path to lib]\Elmish.WPF.Recursive-master\src\Elmish.WPF.Recursive\ViewModel.fs:line 302
   at MS.Internal.DynamicPropertyAccessorImpl.SetValue(Object component, Object value)
   at MS.Internal.Data.PropertyPathWorker.SetValue(Object item, Object value)
   at MS.Internal.Data.ClrBindingWorker.UpdateValue(Object value)
   at System.Windows.Data.BindingExpression.UpdateSource(Object value)
```

I can't seem to find a point in my code where I could handle potentially null values. Is this an issue with Elmish.WPF.Recursive, or am I approaching this problem incorrectly?

I have also attached the sample project that showcases the issue [here](https://1drv.ms/u/s!At_ubPU1PmV4hIcvlaACNUb0lCeO4g).

I appreciate your help.
Thanks!

**Comment by cmeeren** [comment]
Hi! I just became the package maintainer for the official Elmish.WPF repo, and I have created a soon-to-be-merged `rewrite` branch that contains the changes from Elmish.WPF.Recursive as well as quite a few more (this repo will be deleted soon). Would you mind trying with the `rewrite` branch? Alternatively, you can just wait a few days, and I'll merge `rewrite` and release it as 2.0.0-beta-1.

If it's still an issue using the official repo, just post a sample project there that uses the rewrite branch (or 2.0.0-beta-1 after it's released) and I'll happily take a look at it. 👍

**Comment by ChernayaKoshka** [comment]
Fantastic, thank you! I will give the `rewrite` branch a shot and let you know.
